name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: yarn install

      - name: Build and Generate the app
        run: yarn generate

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy the app to VPS
        run: |
          echo "Connecting to VPS..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            echo "Navigating to project directory..."
            cd /root/giveaway_frontend || exit

            echo "Pulling latest changes from repository..."
            git pull || exit

            echo "Removing old files from /var/www/wogiveaway.shop..."
            sudo rm -rf /var/www/wogiveaway.shop/* || exit

            echo "Copying new files to /var/www/wogiveaway.shop..."
            sudo cp -r .output/public/* /var/www/wogiveaway.shop || exit

            echo "Deployment completed successfully."
          EOF
